name: bunnycc_perler
description: "兔可可的拼豆世界 - BunnyCC Perler Bead Designer"
publish_to: 'none'

version: 2.0.5+7

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image: ^4.0.0
  file_picker: ^6.0.0
  pdf: ^3.10.0
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  path_provider: ^2.1.0
  csv: ^5.1.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/changelog.json
    - assets/images/
